"""Zhang reproduction configuration, profiles, reports, and target comparisons."""

from education_roi.reproduction.aggregate import (
    AggregateReproductionResult,
    reproduce_aggregate_target,
)
from education_roi.reproduction.bundle import (
    BUNDLE_SCHEMA_VERSION,
    BundleArtifact,
    BundleIntegrityError,
    ReproductionBundle,
    verify_reproduction_bundle,
    write_reproduction_bundle,
)
from education_roi.reproduction.comparison import (
    ReproductionStatus,
    ReproductionTarget,
    compare_target,
)
from education_roi.reproduction.config import ZhangConfiguration, published_zhang_configuration
from education_roi.reproduction.costs import (
    FALLBACK_ORDER,
    CostCase,
    CostComponents,
    CostEvidence,
    CostLevel,
    CostProvenance,
    CostSelection,
    CostSelectionStatus,
    CostSensitivityResult,
    CostSensitivitySet,
    EducationCostEstimate,
    evaluate_cost_sensitivity,
    select_cost_estimate,
)
from education_roi.reproduction.profiles import (
    CovariateSlopeSpecification,
    EarningsCoefficients,
    EarningsPoint,
    EarningsProfile,
    build_age_earnings_profile,
)
from education_roi.reproduction.quantiles import (
    DECILES,
    RANK_INVARIANCE_WARNING,
    ProfileValidationReport,
    QuantileCashFlow,
    QuantileDefinition,
    QuantileEarningsCoefficients,
    QuantileEarningsPoint,
    QuantileEarningsProfile,
    QuantileIRRResult,
    QuantileProfileFit,
    QuantileSolverMetadata,
    SolverStatus,
    build_quantile_earnings_profile,
    calculate_quantile_irrs,
    validate_profile_against_reference,
)
from education_roi.reproduction.reporting import (
    CertificationStatus,
    ReproductionReport,
    provisional_reproduction_report,
)
from education_roi.reproduction.runner import (
    ProfileFixture,
    ProvisionalRunRequest,
    ProvisionalRunResult,
    TargetObservation,
    run_provisional_reproduction,
)
from education_roi.reproduction.sample_flow import (
    SampleFlowRecord,
    SampleFlowResult,
    zhang_sample_flow,
)

__all__ = [
    "BUNDLE_SCHEMA_VERSION",
    "DECILES",
    "RANK_INVARIANCE_WARNING",
    "AggregateReproductionResult",
    "BundleArtifact",
    "BundleIntegrityError",
    "CertificationStatus",
    "CovariateSlopeSpecification",
    "CostCase",
    "CostComponents",
    "CostEvidence",
    "CostLevel",
    "CostProvenance",
    "CostSelection",
    "CostSelectionStatus",
    "CostSensitivityResult",
    "CostSensitivitySet",
    "EarningsCoefficients",
    "EarningsPoint",
    "EarningsProfile",
    "EducationCostEstimate",
    "FALLBACK_ORDER",
    "ProfileValidationReport",
    "ProfileFixture",
    "QuantileCashFlow",
    "QuantileDefinition",
    "QuantileEarningsCoefficients",
    "QuantileEarningsPoint",
    "QuantileEarningsProfile",
    "QuantileIRRResult",
    "QuantileProfileFit",
    "QuantileSolverMetadata",
    "ProvisionalRunRequest",
    "ProvisionalRunResult",
    "ReproductionReport",
    "ReproductionBundle",
    "ReproductionStatus",
    "ReproductionTarget",
    "SampleFlowRecord",
    "SampleFlowResult",
    "SolverStatus",
    "TargetObservation",
    "ZhangConfiguration",
    "build_age_earnings_profile",
    "build_quantile_earnings_profile",
    "calculate_quantile_irrs",
    "compare_target",
    "evaluate_cost_sensitivity",
    "provisional_reproduction_report",
    "published_zhang_configuration",
    "reproduce_aggregate_target",
    "run_provisional_reproduction",
    "select_cost_estimate",
    "validate_profile_against_reference",
    "verify_reproduction_bundle",
    "write_reproduction_bundle",
    "zhang_sample_flow",
]
