"""Deterministic end-to-end orchestration for provisional Zhang reproduction runs."""

from dataclasses import dataclass
from pathlib import Path

import polars as pl

from education_roi.acs.crosswalk import CrosswalkStatus
from education_roi.reproduction.bundle import ReproductionBundle, write_reproduction_bundle
from education_roi.reproduction.comparison import (
    ReproductionTarget,
    compare_target,
)
from education_roi.reproduction.quantiles import (
    ProfileValidationReport,
    QuantileCashFlow,
    QuantileEarningsCoefficients,
    QuantileProfileFit,
    QuantileSolverMetadata,
    SolverStatus,
    build_quantile_earnings_profile,
    calculate_quantile_irrs,
    validate_profile_against_reference,
)
from education_roi.reproduction.reporting import (
    ReproductionReport,
    provisional_reproduction_report,
)
from education_roi.reproduction.sample_flow import zhang_sample_flow


@dataclass(frozen=True)
class ProfileFixture:
    """One auditable quantile profile and its independently generated reference values."""

    coefficients: QuantileEarningsCoefficients
    solver: QuantileSolverMetadata
    minimum_age: int
    maximum_age: int
    reference: tuple[tuple[int, float], ...] | None
    reference_implementation: str | None
    absolute_tolerance: float = 1e-9
    relative_tolerance: float = 1e-12

    def __post_init__(self) -> None:
        has_reference = self.reference is not None and self.reference_implementation is not None
        if self.solver.status is SolverStatus.CONVERGED and not has_reference:
            raise ValueError("converged profile fixtures require an independent reference")
        if self.solver.status is SolverStatus.FAILED and (
            self.reference is not None or self.reference_implementation is not None
        ):
            raise ValueError("failed profile fixtures cannot claim reference validation")
        if self.reference is not None:
            ages = tuple(age for age, _ in self.reference)
            if len(ages) != len(set(ages)) or ages != tuple(sorted(ages)):
                raise ValueError("profile reference ages must be unique and ordered")


@dataclass(frozen=True)
class TargetObservation:
    """A published target and the value generated by this run, if available."""

    target: ReproductionTarget
    reproduced_value: float | None
    crosswalk_status: CrosswalkStatus
    ambiguity_notes: tuple[str, ...] = ()


@dataclass(frozen=True)
class ProvisionalRunRequest:
    """All versioned inputs required to assemble one provisional reproduction run."""

    configuration_hash: str
    dataset_hashes: tuple[str, ...]
    person_frame: pl.DataFrame
    profile_fixtures: tuple[ProfileFixture, ...]
    cash_flows: tuple[QuantileCashFlow, ...]
    target_observations: tuple[TargetObservation, ...]
    blockers: tuple[str, ...]
    ambiguity_notes: tuple[str, ...]

    def __post_init__(self) -> None:
        if not self.profile_fixtures:
            raise ValueError("a reproduction run requires profile fixtures")
        identities = tuple(
            (item.coefficients.group, item.coefficients.definition.quantile)
            for item in self.profile_fixtures
        )
        if len(identities) != len(set(identities)):
            raise ValueError("profile group and quantile identities must be unique")


@dataclass(frozen=True)
class ProvisionalRunResult:
    report: ReproductionReport
    bundle: ReproductionBundle


def _build_profiles(
    fixtures: tuple[ProfileFixture, ...],
) -> tuple[tuple[QuantileProfileFit, ...], tuple[ProfileValidationReport, ...]]:
    fits: list[QuantileProfileFit] = []
    validations: list[ProfileValidationReport] = []
    ordered = sorted(
        fixtures,
        key=lambda item: (item.coefficients.definition.quantile, item.coefficients.group),
    )
    for fixture in ordered:
        fit = build_quantile_earnings_profile(
            fixture.coefficients,
            fixture.solver,
            minimum_age=fixture.minimum_age,
            maximum_age=fixture.maximum_age,
        )
        fits.append(fit)
        if fit.profile is not None:
            if fixture.reference is None or fixture.reference_implementation is None:
                raise AssertionError("converged fixture validation contract was not enforced")
            validations.append(
                validate_profile_against_reference(
                    fit.profile,
                    dict(fixture.reference),
                    reference_implementation=fixture.reference_implementation,
                    absolute_tolerance=fixture.absolute_tolerance,
                    relative_tolerance=fixture.relative_tolerance,
                )
            )
    return tuple(fits), tuple(validations)


def run_provisional_reproduction(
    request: ProvisionalRunRequest, *, results_root: Path, run_id: str
) -> ProvisionalRunResult:
    """Execute every implemented reproduction stage and write one verified-input bundle."""
    sample_flow = zhang_sample_flow(request.person_frame)
    profiles, validations = _build_profiles(request.profile_fixtures)
    available_hashes = {fit.profile.coefficient_hash for fit in profiles if fit.profile is not None}
    referenced_hashes = {
        profile_hash
        for cash_flow in request.cash_flows
        for profile_hash in (
            cash_flow.option_profile_hash,
            cash_flow.counterfactual_profile_hash,
        )
    }
    missing_hashes = sorted(referenced_hashes - available_hashes)
    if missing_hashes:
        raise ValueError(
            "quantile cash flows reference unavailable profile hashes: " + ", ".join(missing_hashes)
        )
    cash_flows = calculate_quantile_irrs(request.cash_flows)
    comparisons = tuple(
        compare_target(
            observation.target,
            observation.reproduced_value,
            configuration_hash=request.configuration_hash,
            dataset_hashes=request.dataset_hashes,
            crosswalk_status=observation.crosswalk_status,
            ambiguity_notes=observation.ambiguity_notes,
        ).as_dict()
        for observation in sorted(
            request.target_observations, key=lambda item: item.target.target_id
        )
    )
    report = provisional_reproduction_report(
        configuration_hash=request.configuration_hash,
        dataset_hashes=request.dataset_hashes,
        sample_flow=sample_flow.as_dict(),
        profiles=profiles,
        profile_validations=validations,
        cash_flows=cash_flows,
        comparisons=comparisons,
        blockers=request.blockers,
        ambiguity_notes=request.ambiguity_notes,
    )
    bundle = write_reproduction_bundle(report, results_root=results_root, run_id=run_id)
    return ProvisionalRunResult(report, bundle)
