"""Deterministic end-to-end orchestration for provisional Zhang reproduction runs."""

from dataclasses import dataclass
from hashlib import sha256
from json import dumps
from pathlib import Path

import polars as pl

from education_roi.acs.crosswalk import CrosswalkStatus
from education_roi.cashflow import CashFlowSeries, IRRStatus
from education_roi.reproduction.bundle import ReproductionBundle, write_reproduction_bundle
from education_roi.reproduction.comparison import (
    ReproductionTarget,
    compare_target,
)
from education_roi.reproduction.costs import (
    CostLevel,
    CostSelectionStatus,
    CostSensitivityResult,
    CostSensitivitySet,
    EducationCostEstimate,
    evaluate_cost_sensitivity,
    select_cost_estimate,
)
from education_roi.reproduction.quantiles import (
    ProfileValidationReport,
    QuantileCashFlow,
    QuantileEarningsCoefficients,
    QuantileProfileFit,
    QuantileSolverMetadata,
    SolverStatus,
    build_quantile_earnings_profile,
    calculate_quantile_irrs,
    validate_profile_against_reference,
)
from education_roi.reproduction.reporting import (
    ReproductionReport,
    provisional_reproduction_report,
)
from education_roi.reproduction.sample_flow import zhang_sample_flow


@dataclass(frozen=True)
class ProfileFixture:
    """One auditable quantile profile and its independently generated reference values."""

    coefficients: QuantileEarningsCoefficients
    solver: QuantileSolverMetadata
    minimum_age: int
    maximum_age: int
    reference: tuple[tuple[int, float], ...] | None
    reference_implementation: str | None
    absolute_tolerance: float = 1e-9
    relative_tolerance: float = 1e-12

    def __post_init__(self) -> None:
        has_reference = self.reference is not None and self.reference_implementation is not None
        if self.solver.status is SolverStatus.CONVERGED and not has_reference:
            raise ValueError("converged profile fixtures require an independent reference")
        if self.solver.status is SolverStatus.FAILED and (
            self.reference is not None or self.reference_implementation is not None
        ):
            raise ValueError("failed profile fixtures cannot claim reference validation")
        if self.reference is not None:
            ages = tuple(age for age, _ in self.reference)
            if len(ages) != len(set(ages)) or ages != tuple(sorted(ages)):
                raise ValueError("profile reference ages must be unique and ordered")


@dataclass(frozen=True)
class TargetObservation:
    """A published target and the value generated by this run, if available."""

    target: ReproductionTarget
    reproduced_value: float | None
    crosswalk_status: CrosswalkStatus
    ambiguity_notes: tuple[str, ...] = ()


@dataclass(frozen=True)
class PublicCostReproductionFixture:
    """One public-cost fallback request tied to a published reproduction target."""

    reproduction_id: str
    requested_level: CostLevel
    candidates: tuple[EducationCostEstimate, ...]
    sensitivity: CostSensitivitySet | None
    base_incremental_cash_flow: CashFlowSeries | None
    education_ages: tuple[int, ...]
    discount_rate: float
    target: ReproductionTarget
    crosswalk_status: CrosswalkStatus

    def __post_init__(self) -> None:
        if not self.reproduction_id.strip():
            raise ValueError("public cost reproduction ID cannot be empty")
        selection = select_cost_estimate(self.requested_level, self.candidates)
        if selection.status is CostSelectionStatus.INSUFFICIENT_DATA:
            if self.sensitivity is not None or self.base_incremental_cash_flow is not None:
                raise ValueError("insufficient cost selection cannot include modeled cost cases")
            return
        if self.sensitivity is None or self.base_incremental_cash_flow is None:
            raise ValueError("available cost selection requires sensitivity and cash-flow inputs")
        if selection.estimate != self.sensitivity.base:
            raise ValueError("selected public fallback must be the base sensitivity estimate")


def _cost_configuration_hash(
    configuration_hash: str,
    fixture: PublicCostReproductionFixture,
    estimate: EducationCostEstimate | None,
) -> str:
    payload = {
        "configuration_hash": configuration_hash,
        "reproduction_id": fixture.reproduction_id,
        "requested_level": fixture.requested_level.value,
        "education_ages": list(fixture.education_ages),
        "discount_rate": fixture.discount_rate,
        "estimate": None if estimate is None else estimate.as_dict(),
    }
    return sha256(
        dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()
    ).hexdigest()


def _cost_target(
    target: ReproductionTarget, suffix: str, paper_reference_suffix: str
) -> ReproductionTarget:
    return ReproductionTarget(
        f"{target.target_id}:{suffix}",
        f"{target.paper_reference}; {paper_reference_suffix}",
        target.published_value,
        target.absolute_tolerance,
        target.relative_tolerance,
        target.requires_verified_crosswalk,
    )


def evaluate_public_cost_reproductions(
    fixtures: tuple[PublicCostReproductionFixture, ...],
    *,
    configuration_hash: str,
    dataset_hashes: tuple[str, ...],
) -> tuple[tuple[dict[str, object], ...], tuple[dict[str, object], ...]]:
    """Select public fallbacks and compare each cost case with its published target."""
    analyses: list[dict[str, object]] = []
    comparisons: list[dict[str, object]] = []
    identities = tuple(item.reproduction_id for item in fixtures)
    if len(identities) != len(set(identities)):
        raise ValueError("public cost reproduction IDs must be unique")
    for fixture in sorted(fixtures, key=lambda item: item.reproduction_id):
        selection = select_cost_estimate(fixture.requested_level, fixture.candidates)
        if selection.status is CostSelectionStatus.INSUFFICIENT_DATA:
            unavailable_analysis: dict[str, object] = {
                "reproduction_id": fixture.reproduction_id,
                "case": "UNAVAILABLE",
                "status": CostSelectionStatus.INSUFFICIENT_DATA.value,
                "selection": selection.as_dict(),
                "estimate": None,
                "exact_input_eligible": False,
            }
            analyses.append(unavailable_analysis)
            comparison = compare_target(
                _cost_target(fixture.target, "unavailable", "no defensible public cost estimate"),
                None,
                configuration_hash=_cost_configuration_hash(configuration_hash, fixture, None),
                dataset_hashes=dataset_hashes,
                crosswalk_status=fixture.crosswalk_status,
                ambiguity_notes=("public cost fallback returned INSUFFICIENT_DATA",),
            ).as_dict()
            comparison.update(
                {
                    "cost_case": "UNAVAILABLE",
                    "cost_selection_status": CostSelectionStatus.INSUFFICIENT_DATA.value,
                    "cost_irr_delta_from_base": None,
                    "cost_npv_delta_from_base": None,
                }
            )
            comparisons.append(comparison)
            continue
        if fixture.sensitivity is None or fixture.base_incremental_cash_flow is None:
            raise AssertionError("available public cost fixture contract was not enforced")
        results = evaluate_cost_sensitivity(
            fixture.base_incremental_cash_flow,
            fixture.sensitivity,
            education_ages=fixture.education_ages,
            discount_rate=fixture.discount_rate,
        )
        base = next(result for result in results if result.case.value == "BASE")
        base_irr = (
            base.internal_rate_of_return.roots[0]
            if base.internal_rate_of_return.status is IRRStatus.UNIQUE
            else None
        )
        for result in results:
            case_analysis: dict[str, object] = result.as_dict()
            case_analysis.update(
                {
                    "reproduction_id": fixture.reproduction_id,
                    "status": CostSelectionStatus.AVAILABLE.value,
                    "selection": selection.as_dict(),
                }
            )
            analyses.append(case_analysis)
            reproduced = (
                result.internal_rate_of_return.roots[0]
                if result.internal_rate_of_return.status is IRRStatus.UNIQUE
                else None
            )
            comparison = compare_target(
                _cost_target(
                    fixture.target,
                    result.case.value.lower(),
                    f"{result.case.value} public cost substitute",
                ),
                reproduced,
                configuration_hash=_cost_configuration_hash(
                    configuration_hash, fixture, result.estimate
                ),
                dataset_hashes=dataset_hashes,
                crosswalk_status=fixture.crosswalk_status,
                ambiguity_notes=(
                    "methodologically aligned reproduction using a public cost substitute",
                    f"requested {fixture.requested_level.value}; used "
                    f"{result.estimate.actual_level.value}",
                ),
            ).as_dict()
            comparison.update(
                {
                    "cost_case": result.case.value,
                    "cost_selection_status": CostSelectionStatus.AVAILABLE.value,
                    "cost_estimate_id": result.estimate.estimate_id,
                    "cost_evidence": result.estimate.evidence.value,
                    "cost_irr_delta_from_base": (
                        None if reproduced is None or base_irr is None else reproduced - base_irr
                    ),
                    "cost_npv_delta_from_base": result.net_present_value - base.net_present_value,
                }
            )
            comparisons.append(comparison)
    return tuple(analyses), tuple(comparisons)


@dataclass(frozen=True)
class ProvisionalRunRequest:
    """All versioned inputs required to assemble one provisional reproduction run."""

    configuration_hash: str
    dataset_hashes: tuple[str, ...]
    person_frame: pl.DataFrame
    profile_fixtures: tuple[ProfileFixture, ...]
    cash_flows: tuple[QuantileCashFlow, ...]
    target_observations: tuple[TargetObservation, ...]
    blockers: tuple[str, ...]
    ambiguity_notes: tuple[str, ...]
    cost_analysis: tuple[CostSensitivityResult, ...] = ()
    public_cost_reproductions: tuple[PublicCostReproductionFixture, ...] = ()

    def __post_init__(self) -> None:
        if not self.profile_fixtures:
            raise ValueError("a reproduction run requires profile fixtures")
        identities = tuple(
            (item.coefficients.group, item.coefficients.definition.quantile)
            for item in self.profile_fixtures
        )
        if len(identities) != len(set(identities)):
            raise ValueError("profile group and quantile identities must be unique")


@dataclass(frozen=True)
class ProvisionalRunResult:
    report: ReproductionReport
    bundle: ReproductionBundle


def _build_profiles(
    fixtures: tuple[ProfileFixture, ...],
) -> tuple[tuple[QuantileProfileFit, ...], tuple[ProfileValidationReport, ...]]:
    fits: list[QuantileProfileFit] = []
    validations: list[ProfileValidationReport] = []
    ordered = sorted(
        fixtures,
        key=lambda item: (item.coefficients.definition.quantile, item.coefficients.group),
    )
    for fixture in ordered:
        fit = build_quantile_earnings_profile(
            fixture.coefficients,
            fixture.solver,
            minimum_age=fixture.minimum_age,
            maximum_age=fixture.maximum_age,
        )
        fits.append(fit)
        if fit.profile is not None:
            if fixture.reference is None or fixture.reference_implementation is None:
                raise AssertionError("converged fixture validation contract was not enforced")
            validations.append(
                validate_profile_against_reference(
                    fit.profile,
                    dict(fixture.reference),
                    reference_implementation=fixture.reference_implementation,
                    absolute_tolerance=fixture.absolute_tolerance,
                    relative_tolerance=fixture.relative_tolerance,
                )
            )
    return tuple(fits), tuple(validations)


def run_provisional_reproduction(
    request: ProvisionalRunRequest, *, results_root: Path, run_id: str
) -> ProvisionalRunResult:
    """Execute every implemented reproduction stage and write one verified-input bundle."""
    sample_flow = zhang_sample_flow(request.person_frame)
    profiles, validations = _build_profiles(request.profile_fixtures)
    available_hashes = {fit.profile.coefficient_hash for fit in profiles if fit.profile is not None}
    referenced_hashes = {
        profile_hash
        for cash_flow in request.cash_flows
        for profile_hash in (
            cash_flow.option_profile_hash,
            cash_flow.counterfactual_profile_hash,
        )
    }
    missing_hashes = sorted(referenced_hashes - available_hashes)
    if missing_hashes:
        raise ValueError(
            "quantile cash flows reference unavailable profile hashes: " + ", ".join(missing_hashes)
        )
    cash_flows = calculate_quantile_irrs(request.cash_flows)
    comparisons = tuple(
        compare_target(
            observation.target,
            observation.reproduced_value,
            configuration_hash=request.configuration_hash,
            dataset_hashes=request.dataset_hashes,
            crosswalk_status=observation.crosswalk_status,
            ambiguity_notes=observation.ambiguity_notes,
        ).as_dict()
        for observation in sorted(
            request.target_observations, key=lambda item: item.target.target_id
        )
    )
    public_cost_analysis, public_cost_comparisons = evaluate_public_cost_reproductions(
        request.public_cost_reproductions,
        configuration_hash=request.configuration_hash,
        dataset_hashes=request.dataset_hashes,
    )
    comparisons = tuple(
        sorted(
            (*comparisons, *public_cost_comparisons),
            key=lambda item: str(item.get("target_id", "")),
        )
    )
    sample_records: tuple[dict[str, object], ...] = tuple(
        {
            "step": record.step,
            "description": record.description,
            "unweighted_n": record.unweighted_n,
            "weighted_n": record.weighted_n,
        }
        for record in sample_flow.records
    )
    report = provisional_reproduction_report(
        configuration_hash=request.configuration_hash,
        dataset_hashes=request.dataset_hashes,
        sample_flow=sample_records,
        profiles=profiles,
        profile_validations=validations,
        cash_flows=cash_flows,
        comparisons=comparisons,
        blockers=request.blockers,
        ambiguity_notes=request.ambiguity_notes,
        cost_analysis=(
            *(item.as_dict() for item in request.cost_analysis),
            *public_cost_analysis,
        ),
    )
    bundle = write_reproduction_bundle(report, results_root=results_root, run_id=run_id)
    return ProvisionalRunResult(report, bundle)
